apiVersion: v2
name: keycloak-helm
version: 0.0.1
appVersion: 20.0.3
description: Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
maintainers:
  - name: najeeb rifaat
    email: mohamme89d@gmail.com

dependencies:
  - name: keycloak
    version: 13.0.5
    repository: https://charts.bitnami.com/bitnami
