postgresql:
  auth:
    username: keycloak
    password: keycloak
  primary:
    persistence:
      size: 4Gi

keycloak:
  replicaCount: 2
  auth:
    adminUser: keycloak
    adminPassword: keycloak

  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: keycloak
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: keycloak
    - name: KC_PROXY
      value: "passthrough"
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=80.0
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

  sidecars: |
    - name: keycloak-migrations
      image: klg71/keycloakmigration
      env:
      - name: ADMIN_USER
        value: keycloak
      - name: ADMIN_PASSWORD
        value: keycloak
      - name: BASEURL
        value: http://localhost:8080
      - name: KEYCLOAK_CHANGELOG
        value: /migration/keycloak-changelog.yaml
      - name: WAIT_FOR_KEYCLOAK
        value: "true"
      - name: STAY_IDLE
        value: "true"
      volumeMounts:
        - name: migrations
          mountPath: /migration
          readOnly: true

  extraVolumes: |
    - name: migrations
      configMap:
        name: keycloak-migrations

  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    path: "/"
    hostname: keycloak.k8s.ingress

  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 386Mi
      cpu: 250m

migrations:
  - id: "M001-20221219"
    author: najee89b
    changes:
      - addRealm:
          id: najeeb
          name: najeeb
          enabled: true
  - id: "M002-20221219"
    author: najee89b
    changes:
      - addSimpleClient:
          realm: najeeb
          clientId: todo-app
          enabled: true
          publicClient: true
      - updateClient:
          realm: najeeb
          clientId: todo-app
          enabled: true
          directAccessGrantEnabled: false
          redirectUris:
            - http://localhost:8080/
            - http://localhost:3000/
            - http://localhost:5000/
            - http://localhost:5173/
          webOrigins:
            - http://localhost:8080
            - http://localhost:3000
            - http://localhost:5000
            - http://localhost:5173
          attributes:
            'pkce.code.challenge.method': 'S256'
            'client.session.idle.timeout': '120'
            'access.token.lifespan': '60'
